/**
 * `dialecte coverage` — generate COMPLETE, config-driven type-coverage probes:
 *   • coverage.surface.generated.ts — type fan-out over every element × per-element generic
 *   • coverage.calls.generated.ts   — valid calls for every core verb × every (parent,child) edge
 *   • coverage.deep.generated.ts    — deepest-path nested getTree/findDescendants (recursion cost)
 * Dialect-agnostic; driven by the resolved DialecteConfig (binding + constantsDir + out).
 * Also exports `genNarrowing` (used by the `narrowing` gate) + `loadSchema` (shared schema loader).
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

import { resolveTargets, tsconfigOf, type Binding } from '../lib/config.ts'
import { discoverMethodPaths } from '../lib/discover.ts'
import { formatFiles, formatOptsFromArgv } from '../lib/format.ts'

type AttrDetail = {
	required?: boolean
	fixed?: string
	facets?: { enumeration?: readonly string[] }
}
type ElementDef = { attributes?: { details?: Record<string, AttrDetail> } }
export type DialecteSchema = {
	elements: readonly string[]
	children: Record<string, readonly string[]>
	singletons: readonly string[]
	definition: Record<string, ElementDef>
	/** Optional — present when the dialect's constants export ROOT_ELEMENT. */
	root?: string
}

const ELEMENT_GENERICS = [
	'Ref',
	'RawRecord',
	'TrackedRecord',
	'TreeRecord',
	'AttributesOf',
	'AttributesValueObjectOf',
	'FullAttributeObjectOf',
	'ChildrenOf',
	'ParentsOf',
	'DescendantsOf',
	'AncestorsOf',
	'ParentRelationship',
	'ChildRelationship',
	'Attribute',
	'QualifiedAttribute',
] as const

export function refsOf(b: Binding) {
	if (b.kind === 'namespace') {
		return {
			imports: [`import type { ${b.name} } from '${b.import}'`],
			elementsOf: `${b.name}.ElementsOf`,
			query: `${b.name}.Query`,
			transaction: `${b.name}.Transaction`,
			generic: (g: string, e: string) => `${b.name}.${g}<${e}>`,
			nullary: (t: string) => `${b.name}.${t}`,
		}
	}
	return {
		imports: [
			`import type * as ${b.coreAlias} from '${b.coreImport}'`,
			`import type { ${b.configType} } from '${b.configImport}'`,
		],
		elementsOf: `${b.coreAlias}.ElementsOf<${b.configType}>`,
		query: `${b.coreAlias}.Query<${b.configType}>`,
		transaction: `${b.coreAlias}.Transaction<${b.configType}>`,
		generic: (g: string, e: string) => `${b.coreAlias}.${g}<${b.configType}, ${e}>`,
		nullary: (t: string) => `${b.coreAlias}.${t}<${b.configType}>`,
	}
}

export const attrValue = (d: AttrDetail | undefined): string => {
	if (d?.fixed) return d.fixed
	const enums = d?.facets?.enumeration?.filter((v) => v !== '')
	return enums?.length ? enums[0] : 'x'
}

export function genSurface(b: Binding): string {
	const r = refsOf(b)
	const lines = [
		`// AUTO-GENERATED by \`dialecte coverage\` — do not edit. Complete per-element TYPE coverage.`,
		...r.imports,
		'',
	]
	const names: string[] = []
	for (const g of ELEMENT_GENERICS) {
		lines.push(`type All_${g} = { [E in ${r.elementsOf}]: ${r.generic(g, 'E')} }[${r.elementsOf}]`)
		names.push(`All_${g}`)
	}
	lines.push('', `export type CoverageSurface = [${names.join(', ')}]`, '')
	return lines.join('\n')
}

export function genCalls(schema: DialecteSchema, b: Binding): string {
	const r = refsOf(b)
	const childCap = Number(process.env.COVERAGE_CHILD_CAP || Infinity)
	const singletons = new Set(schema.singletons)
	const ref = (e: string) =>
		singletons.has(e) ? `{ tagName: '${e}' }` : `{ tagName: '${e}', id: 'x' }`
	const details = (e: string) => schema.definition[e]?.attributes?.details ?? {}
	const attrsObj = (e: string) => {
		const d = details(e)
		const req = Object.keys(d).filter((a) => d[a]?.required)
		return req.length ? `{ ${req.map((a) => `'${a}': '${attrValue(d[a])}'`).join(', ')} }` : '{}'
	}
	const L = [
		`// AUTO-GENERATED by \`dialecte coverage\` — do not edit. Complete valid-call coverage (core verbs × schema).`,
		...r.imports,
		`declare const q: ${r.query}`,
		`declare const tx: ${r.transaction}`,
		'',
		`export async function _coverageCalls() {`,
	]
	for (const e of schema.elements) {
		const rf = ref(e)
		L.push(`\tawait q.getRecordsByTagName('${e}')`)
		L.push(`\tawait q.getRecord(${rf})`)
		L.push(`\tawait q.getAttributes(${rf})`)
		L.push(`\tawait q.getAttributes(${rf}, { fullObject: true })`)
		L.push(`\tawait q.getTree(${rf})`)
		L.push(`\tawait q.findDescendants(${rf})`)
		L.push(`\tawait tx.update(${rf}, { attributes: {} })`)
		L.push(`\tawait tx.delete(${rf})`)
		const names = Object.keys(details(e))
		if (names.length) L.push(`\tawait q.getAttribute(${rf}, { name: '${names[0]}' })`)
		for (const c of (schema.children[e] ?? []).slice(0, childCap)) {
			L.push(`\tawait q.getChild(${rf}, '${c}')`)
			L.push(`\tawait q.getChildren(${rf}, '${c}')`)
			L.push(`\tawait tx.addChild(${rf}, { tagName: '${c}', attributes: ${attrsObj(c)} })`)
			L.push(`\tawait tx.ensureChild(${rf}, { tagName: '${c}', attributes: ${attrsObj(c)} })`)
		}
	}
	L.push('}', '')
	return L.join('\n')
}

/** A trivial import-baseline file (auto-generated, so it's never hand-maintained). */
export function genBaseline(b: Binding): string {
	const r = refsOf(b)
	return [
		`// AUTO-GENERATED by \`dialecte coverage\` — do not edit. Import baseline for bench subtraction.`,
		...r.imports,
		'',
		`export type _Element = ${r.elementsOf}`,
		'',
	].join('\n')
}

/** Greedy deepest acyclic child-path from `root`, preferring high-fan-out children (depth-capped). */
export function deepestPath(
	root: string,
	children: Record<string, readonly string[]>,
	cap = 8,
): string[] {
	const visited = new Set<string>()
	const path: string[] = []
	let cur: string | undefined = root
	while (cur && path.length < cap && !visited.has(cur)) {
		path.push(cur)
		visited.add(cur)
		const kids: string[] = (children[cur] ?? []).filter((c) => !visited.has(c))
		cur = [...kids].sort((a, b) => (children[b]?.length ?? 0) - (children[a]?.length ?? 0))[0]
	}
	return path
}

const nestedSelect = (tags: string[]): string =>
	tags.length ? `{ ${tags[0]}: ${nestedSelect(tags.slice(1))} }` : 'true'

/** Deepest-path nested getTree/findDescendants — exercises the recursive TreeSelect/collect cost. */
export function genDeepProbe(schema: DialecteSchema, b: Binding): string {
	const r = refsOf(b)
	const singletons = new Set(schema.singletons)
	const root = schema.root ?? schema.singletons[0] ?? schema.elements[0]
	const rootRef = singletons.has(root)
		? `{ tagName: '${root}' }`
		: `{ tagName: '${root}', id: 'x' }`
	const path = deepestPath(root, schema.children)
	const nested = nestedSelect(path.slice(1))
	const L = [
		`// AUTO-GENERATED by \`dialecte coverage\` — do not edit. Deepest-path recursion probe.`,
		...r.imports,
		`declare const q: ${r.query}`,
		'',
		`export async function _coverageDeep() {`,
	]
	if (path.length > 1) {
		L.push(`\tawait q.getTree(${rootRef}, { select: ${nested} })`)
		L.push(`\tawait q.findDescendants(${rootRef}, { collect: ${nested} })`)
	} else {
		L.push(`\tawait q.getTree(${rootRef})`)
		L.push(`\tawait q.findDescendants(${rootRef})`)
	}
	L.push('}', '')
	return L.join('\n')
}

/** A self-contained entry that declares q/tx/doc/project — fed to `discoverMethodPaths`. */
export function discoveryEntry(b: Binding): string {
	const r = refsOf(b)
	return [
		...r.imports,
		`declare const q: ${r.query}`,
		`declare const tx: ${r.transaction}`,
		`declare const doc: ${r.nullary('Document')}`,
		`declare const project: ${r.nullary('Project')}`,
		`export { q, tx, doc, project }`,
		'',
	].join('\n')
}

/**
 * Full public method-surface probe — instantiates params + return of EVERY discovered method (core verbs
 * AND the extension/domain groups: history, reference, dataModel, template, cleanUp, presentation, …).
 * `methodPaths` come from `discoverMethodPaths`. `Parameters<…>[0]` + `Awaited<ReturnType<…>>` are forced
 * computations, so referencing them all in `CoverageApi` makes tsc instantiate the whole surface — what
 * `bench` measures as `coverage: api` and the `narrowing` gate type-checks. (A pure mapped-type fan-out
 * does NOT force instantiation — measured +131 — hence this explicit per-method form.)
 */
export function genApiProbe(b: Binding, methodPaths: readonly string[]): string {
	const r = refsOf(b)
	const L = [
		`// AUTO-GENERATED by \`dialecte coverage\` — do not edit. Full method-surface instantiation (incl. extensions).`,
		...r.imports,
		`declare const q: ${r.query}`,
		`declare const tx: ${r.transaction}`,
		`declare const doc: ${r.nullary('Document')}`,
		`declare const project: ${r.nullary('Project')}`,
		'',
	]
	const refs: string[] = []
	methodPaths.forEach((p, i) => {
		// Whole Parameters tuple (not [0]) — instantiates every param AND avoids TS2493 on zero-arg methods.
		L.push(`export type MP_${i} = Parameters<typeof ${p}>`)
		L.push(`export type MR_${i} = Awaited<ReturnType<typeof ${p}>>`)
		refs.push(`MP_${i}`, `MR_${i}`)
	})
	L.push('', `export type CoverageApi = [${refs.join(', ')}]`, '')
	return L.join('\n')
}

/**
 * Exhaustive, schema-derived type-narrowing assertions (the IntelliSense safety net). Type-checked by
 * the `narrowing` gate; a false assertion is a TS error in this file. Portable across dialects + core:
 * uses only the guaranteed schema (elements/children/singletons/attrs) + structural namespace checks.
 */
export function genNarrowing(schema: DialecteSchema, b: Binding): string {
	const r = refsOf(b)
	const singletons = new Set(schema.singletons)
	const L: string[] = [
		`// AUTO-GENERATED by \`dialecte narrowing\` — do not edit. Exhaustive narrowing assertions.`,
		...r.imports,
		'',
		`type Expect<T extends true> = T`,
		`type Equal<A, B> =`,
		`\t(<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false`,
		`type Includes<Member, Union> = Member extends Union ? true : false`,
		`type IdOptional<E extends ${r.elementsOf}> = undefined extends ${r.generic('Ref', 'E')}['id'] ? true : false`,
		'',
	]
	let i = 0
	const a = (body: string) => L.push(`type _${i++} = Expect<${body}>`)

	// — global invariants —
	a(`Equal<Includes<string, ${r.elementsOf}>, false>`) // element union not widened to string
	a(`Includes<${r.generic('ParentsOf', r.elementsOf)}, ${r.elementsOf}>`) // all parents ⊆ elements
	a(`Includes<${r.generic('DescendantsOf', r.elementsOf)}, ${r.elementsOf}>`) // all descendants ⊆ elements
	a(`Includes<'query', keyof ${r.nullary('Document')}>`)
	a(`Includes<'transaction', keyof ${r.nullary('Document')}>`)
	a(`Includes<'query', keyof ReturnType<${r.nullary('Project')}['openDocument']>>`)
	if (schema.root) {
		a(`Equal<${r.nullary('RootElementOf')}, '${schema.root}'>`)
		a(`Includes<'${schema.root}', ${r.nullary('SingletonElementsOf')}>`)
	}
	for (const s of schema.singletons) a(`Includes<'${s}', ${r.nullary('SingletonElementsOf')}>`)

	// — per element: membership, record tagName, Ref id-requiredness, first attribute —
	for (const e of schema.elements) {
		a(`Includes<'${e}', ${r.elementsOf}>`)
		a(`Equal<${r.generic('TrackedRecord', `'${e}'`)}['tagName'], '${e}'>`)
		a(`Equal<IdOptional<'${e}'>, ${singletons.has(e) ? 'true' : 'false'}>`)
		const attrs = Object.keys(schema.definition[e]?.attributes?.details ?? {})
		if (attrs.length) a(`Includes<'${attrs[0]}', ${r.generic('AttributesOf', `'${e}'`)}>`)
	}

	// — per child edge: child ∈ ChildrenOf<parent> —
	for (const [p, kids] of Object.entries(schema.children))
		for (const c of kids) a(`Includes<'${c}', ${r.generic('ChildrenOf', `'${p}'`)}>`)

	L.push('')
	return L.join('\n')
}

/** Load + validate a dialect's leaf generated constants into a DialecteSchema. Shared by commands. */
export async function loadSchema(absConstantsDir: string): Promise<DialecteSchema> {
	const constantsPath = join(absConstantsDir, 'constants.generated.ts')
	const definitionPath = join(absConstantsDir, 'definition.generated.ts')
	for (const p of [constantsPath, definitionPath])
		if (!existsSync(p)) throw new Error(`expected ${p}`)
	// Import leaf generated files DIRECTLY (pure data) — Node's native TS strip handles them, no tsx.
	const mod: Record<string, unknown> = {
		...(await import(pathToFileURL(constantsPath).href)),
		...(await import(pathToFileURL(definitionPath).href)),
	}
	for (const k of ['ELEMENT_NAMES', 'CHILDREN', 'SINGLETON_ELEMENTS', 'DEFINITION'])
		if (!(k in mod)) throw new Error(`${absConstantsDir} leaf files do not export ${k}`)
	return {
		elements: mod.ELEMENT_NAMES as string[],
		children: mod.CHILDREN as Record<string, readonly string[]>,
		singletons: mod.SINGLETON_ELEMENTS as string[],
		definition: mod.DEFINITION as never,
		root: typeof mod.ROOT_ELEMENT === 'string' ? mod.ROOT_ELEMENT : undefined,
	}
}

/** Write the probe files into `outDir`; returns the absolute paths written. */
export function generateCoverage(
	schema: DialecteSchema,
	binding: Binding,
	outDir: string,
	methodPaths?: readonly string[],
): string[] {
	mkdirSync(outDir, { recursive: true })
	const written: [string, string][] = [
		[join(outDir, 'coverage.surface.generated.ts'), genSurface(binding)],
		[join(outDir, 'coverage.calls.generated.ts'), genCalls(schema, binding)],
		[join(outDir, 'coverage.deep.generated.ts'), genDeepProbe(schema, binding)],
		[join(outDir, 'baseline.ts'), genBaseline(binding)],
	]
	if (methodPaths)
		written.push([join(outDir, 'coverage.api.generated.ts'), genApiProbe(binding, methodPaths)])
	for (const [path, content] of written) writeFileSync(path, content)
	const edges = Object.values(schema.children).reduce((a, v) => a + (v?.length ?? 0), 0)
	console.log(`coverage: ${schema.elements.length} elements, ${edges} child edges → ${outDir}`)
	return written.map(([path]) => path)
}

export async function run(argv: string[]): Promise<void> {
	const targets = resolveTargets(argv)
	if (!targets.length)
		throw new Error(
			'coverage: no dialect versions discovered (src/<version>/definition/*.generated.ts). Pass --constants-dir, or add a "dialecte" config.',
		)
	const fmt = formatOptsFromArgv(argv)
	const tsconfig = tsconfigOf(argv)
	for (const t of targets) {
		const schema = await loadSchema(resolve(process.cwd(), t.constantsDir))
		console.log(`[${t.version}]`)
		// Discover the full method surface (incl. extension/domain groups) → the coverage.api probe.
		let methodPaths: string[] | undefined
		try {
			methodPaths = discoverMethodPaths(discoveryEntry(t.binding), tsconfig, process.cwd())
		} catch {
			console.warn(
				`  ⚠ [${t.version}] method-surface discovery failed — skipping coverage.api probe`,
			)
		}
		const written = generateCoverage(
			schema,
			t.binding,
			resolve(process.cwd(), t.outDir),
			methodPaths,
		)
		formatFiles(process.cwd(), written, fmt)
	}
}
